name: Build Tests

on: [push, pull_request]

jobs:
  build:
    name: Building RESTEasy with Maven
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build and install RESTEasy
      run: mvn install

  rpm-build-test:
    name: RPM Build Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'fedora:latest'
    container: ${{ matrix.os }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        dnf install -y dnf-plugins-core rpm-build
        dnf builddep -y --spec resteasy.spec

    - name: Build RPM package
      run: rpmbuild -ba
